name: mctl
description: A CLI app to creating and managing server apps using Momentum Web Framework.
version: 0.1.1

homepage: https://github.com/x-i-f-r-a/mcli

environment:
  sdk: '>=2.17.5 <3.0.0'

platforms:
  linux:
  macos:
  windows:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies: 
  http: ^0.13.4
  path: ^1.8.0
  watcher: ^1.0.1
  args: ^2.3.1

